package com.example.binittowinit.database;

import android.content.Context;

import androidx.annotation.NonNull;
import androidx.room.Database;
import androidx.room.Room;
import androidx.room.RoomDatabase;
import androidx.room.migration.Migration;
import androidx.sqlite.db.SupportSQLiteDatabase;

/**
 * AndroidX Room Database for "Bin It to Win It".
 * <p>
 * Provides robust SQLite abstraction, compile-time query syntax validation,
 * automated migration verification, and thread-safe instance management.
 * </p>
 */
@Database(entities = {ScoreEntry.class}, version = 2, exportSchema = true)
public abstract class AppDatabase extends RoomDatabase {

    private static final String DATABASE_NAME = "binit_game.db";
    private static volatile AppDatabase INSTANCE;

    /**
     * Returns the Data Access Object (DAO) for leaderboard score operations.
     *
     * @return Score DAO implementation generated by Room.
     */
    public abstract ScoreDao scoreDao();

    /**
     * Pre-defined automated migration from legacy SQLite (version 1) to Room schema (version 2),
     * ensuring existing high scores and player records are safely preserved.
     */
    public static final Migration MIGRATION_1_2 = new Migration(1, 2) {
        @Override
        public void migrate(@NonNull SupportSQLiteDatabase database) {
            database.execSQL("CREATE TABLE IF NOT EXISTS leaderboard_new ("
                    + "id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "
                    + "player_name TEXT NOT NULL, "
                    + "score INTEGER NOT NULL, "
                    + "items_sorted INTEGER NOT NULL DEFAULT 0, "
                    + "critters_rescued INTEGER NOT NULL DEFAULT 0, "
                    + "timestamp TEXT NOT NULL)");
            database.execSQL("INSERT INTO leaderboard_new (id, player_name, score, items_sorted, critters_rescued, timestamp) "
                    + "SELECT id, player_name, score, items_sorted, critters_rescued, timestamp FROM leaderboard");
            database.execSQL("DROP TABLE leaderboard");
            database.execSQL("ALTER TABLE leaderboard_new RENAME TO leaderboard");
        }
    };

    /**
     * Returns the singleton instance of {@link AppDatabase}.
     *
     * @param context Application context.
     * @return Thread-safe Room database instance.
     */
    public static AppDatabase getInstance(Context context) {
        if (INSTANCE == null) {
            synchronized (AppDatabase.class) {
                if (INSTANCE == null) {
                    INSTANCE = Room.databaseBuilder(
                            context.getApplicationContext(),
                            AppDatabase.class,
                            DATABASE_NAME)
                            .addMigrations(MIGRATION_1_2)
                            .fallbackToDestructiveMigration()
                            .build();
                }
            }
        }
        return INSTANCE;
    }
}
